swagger: "2.0"
info:
  title: Best(Customer/Category/Brand/Keyword/Topic) API
  description: 고객/카테고리/브랜드/키워드/토픽 베스트 API 입니다.
  version: 1.0.0
host: 10.118.242.121:10380
schemes:
  - http
tags:
  - name: BEST-API
paths:
  /econapi/mach.ecn?job=userBest:
    get:
      tags:
        - BEST-API
      summary: 고객 베스트 조회 API
      description: 고객 베스트 데이터용 API 입니다.
      produces:
        - application/json
      parameters:
        - name: limit
          type: integer
          required: true
          in: query
          default: 100
        - name: skip
          type: integer
          required: true
          in: query
          default: 0
        - name: sort
          type: string
          required: true
          in: query
          default: sort_2
        - name: direction
          type: string
          required: true
          in: query
          default: asc
        - name: filter_1
          type: string
          required: true
          in: query
          description: 성별(A/M/F)
        - name: filter_2
          type: string
          required: true
          in: query
          description: 나이(A/20/30/40/50)
      responses:
        200:
          description: OK
          schema:
            type: object
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /econapi/mach.ecn?job=catgoryBest:
    get:
      tags:
        - BEST-API
      summary: 카테고리 베스트 조회 API
      description: 카테고리 베스트 데이터용 API 입니다.
      produces:
        - application/json
      parameters:
        - name: limit
          type: integer
          required: true
          in: query
          default: 100
        - name: skip
          type: integer
          required: true
          in: query
          default: 0
        - name: sort
          type: string
          required: true
          in: query
          default: sort_2
        - name: direction
          type: string
          required: true
          in: query
          default: asc
        - name: filter_1
          type: string
          required: true
          in: query
          description: 몰코드
        - name: filter_2
          type: string
          required: true
          in: query
          description: 대카테고리 No
        - name: filter_3
          type: string
          required: true
          in: query
          description: 중카테고리 No
      responses:
        200:
          description: OK
          schema:
            type: object
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found