swagger: "2.0"
info:
  title: Category API
  description: 표준카테고리 API 입니다.
  version: 1.0.0
host: 10.118.242.16:10380
schemes:
  - http
tags:
  - name: CATEGORY-API
paths:
  /econ/search?collectionId=5&volume=general1:
    get:
      tags:
        - CATEGORY-API
      summary: 표준 카테고리 조회 API
      description: 표준 카테고리용 API 입니다.
      produces:
        - application/json
      parameters:
        - name: limit
          type: integer
          required: true
          in: query
          default: 2
        - name: skip
          type: integer
          required: true
          in: query
          default: 0
        - name: f1
          type: string
          required: false
          in: query
          description: 표준 카테고리 아이디
        - name: f2
          type: string
          required: false
          in: query
          description: 부모 표준 카테고리 아이디
        - name: f3
          type: integer
          required: false
          in: query
          description: 깊이
        - name: f4
          type: boolean
          required: false
          in: query
          description: 리프여부(Y/N)
        - name: s1
          type: integer
          required: false
          in: query
          description: 우선순위
      responses:
        200:
          description: OK
          schema:
            type: object
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
